# Generated by Django 4.1.4 on 2022-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('number', models.IntegerField()),
                ('there_is', models.BooleanField(default=False)),
                ('data_create', models.DateTimeField()),
            ],
        ),
    ]
