# Generated by Django 4.1.4 on 2022-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_category_alter_tovar_options_alter_tovar_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='number',
            field=models.IntegerField(default=False, verbose_name='Номер'),
        ),
    ]
